<{if !$pjax}>
<{include file='../Public/header.phtml'}>
<{else}>
<{/if}>
<div class="page-content" id="main">
    <div class="page-header">
        <h1>Treeview
            <small><i class="icon-double-angle-right"></i> with
                selectable items(single &amp; multiple) and custom icons
            </small>
        </h1>
    </div>
    <!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12"><!-- PAGE CONTENT BEGINS -->

            <div class="row">
                <div class="col-sm-6">
                    <div class="widget-box">
                        <div class="widget-header header-color-blue2">
                            <h4 class="lighter smaller">Choose Categories</h4>
                        </div>

                        <div class="widget-body">
                            <div class="widget-main padding-8">
                                <div id="tree1" class="tree"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="widget-box">
                        <div class="widget-header header-color-green2">
                            <h4 class="lighter smaller">Browse Files</h4>
                        </div>

                        <div class="widget-body">
                            <div class="widget-main padding-8">
                                <div id="tree2" class="tree"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                var $assets = "assets";//this will be used in fuelux.tree-sampledata.js
            </script>
            <!-- PAGE CONTENT ENDS --></div>
        <!-- /.col --></div>
    <!-- /.row --></div>
<!-- /.page-content -->
</div>
<!-- /.main-content -->

<div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-xs btn-warning ace-settings-btn"
         id="ace-settings-btn"><i class="icon-cog bigger-150"></i></div>

    <div class="ace-settings-box" id="ace-settings-box">
        <div>
            <div class="pull-left"><select id="skin-colorpicker" class="hide">
                    <option data-skin="default" value="#438EB9">#438EB9</option>
                    <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                    <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                    <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                </select></div>
            <span>&nbsp; Choose Skin</span></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-navbar"/> <label class="lbl"
                                                      for="ace-settings-navbar"> Fixed Navbar</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-sidebar"/> <label class="lbl"
                                                       for="ace-settings-sidebar"> Fixed Sidebar</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-breadcrumbs"/> <label class="lbl"
                                                           for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
        </div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-rtl"/> <label class="lbl" for="ace-settings-rtl">
                Right To Left (rtl)</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-add-container"/> <label class="lbl"
                                                             for="ace-settings-add-container"> Inside <b>.container</b>
            </label></div>
    </div>
</div>
<!-- /#ace-settings-container -->
</div>
<!-- /.main-container-inner -->

<a href="#" id="btn-scroll-up"
   class="btn-scroll-up btn btn-sm btn-inverse"> <i
        class="icon-double-angle-up icon-only bigger-110"></i> </a>
</div>
<!-- /.main-container -->

<!-- basic scripts -->


<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='http://www.ace.com/public/assets/js/jquery-1.10.2.min.js'>" + "<" + "/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if ("ontouchend" in document) document.write("<script src='http://www.ace.com/public/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<script type="text/javascript">
    jQuery(function ($) {
        $('#tree1').ace_tree({
            dataSource: treeDataSource,
            multiSelect: true,
            loadingHTML: '<div class="tree-loading"><i class="icon-refresh icon-spin blue"></i></div>',
            'open-icon': 'icon-minus',
            'close-icon': 'icon-plus',
            'selectable': true,
            'selected-icon': 'icon-ok',
            'unselected-icon': 'icon-remove'
        });
        $('#tree2').ace_tree({
            dataSource: treeDataSource2,
            loadingHTML: '<div class="tree-loading"><i class="icon-refresh icon-spin blue"></i></div>',
            'open-icon': 'icon-folder-open',
            'close-icon': 'icon-folder-close',
            'selectable': false,
            'selected-icon': null,
            'unselected-icon': null
        });


        /**
         $('#tree1').on('loaded', function (evt, data) {
		});

         $('#tree1').on('opened', function (evt, data) {
		});

         $('#tree1').on('closed', function (evt, data) {
		});

         $('#tree1').on('selected', function (evt, data) {
		});
         */
    });
</script>
<div style="display: none"></div>
</body>
</html>
