<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title><{$title}> - Bootstrap后台管理系统模版Ace下载</title>
		<meta name="keywords" content="Bootstrap模版,Bootstrap模版下载,Bootstrap教程,Bootstrap中文" />
		<meta name="description" content="站长素材提供Bootstrap模版,Bootstrap教程,Bootstrap中文翻译等相关Bootstrap插件下载" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- basic styles start-->
        <link rel="stylesheet" href="/public/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/public/assets/css/font-awesome.min.css" />
        <!--[if IE 7]>
        <link rel="stylesheet" href="/public/assets/css/font-awesome-ie7.min.css" />
        <![endif]-->
        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/select2.css" />

        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/prettify.css" />

        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/dropzone.css" />

        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/colorbox.css" />

        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/jquery-ui-1.10.3.custom.min.css" />
        <link rel="stylesheet" href="/public/assets/css/jquery.gritter.css" />

        <!-- page specific plugin styles -->
        <link rel="stylesheet" href="/public/assets/css/jquery-ui-1.10.3.full.min.css" />
        <link rel="stylesheet" href="/public/assets/css/datepicker.css" />
        <link rel="stylesheet" href="/public/assets/css/ui.jqgrid.css" />

        <link rel="stylesheet" href="/public/assets/css/ace.min.css" />
        <link rel="stylesheet" href="/public/assets/css/ace-rtl.min.css" />
        <link rel="stylesheet" href="/public/assets/css/ace-skins.min.css" />

        <!--[if lte IE 8]>
        <link rel="stylesheet" href="/public/assets/css/ace-ie.min.css" />
        <![endif]-->
        <!-- basic styles end-->


        <!-- common script start -->
        <!-- ace settings handler -->
        <script src="/public/assets/js/ace-extra.min.js"></script>
        <!--[if lt IE 9]>
        <script src="/public/assets/js/html5shiv.js"></script>
        <script src="/public/assets/js/respond.min.js"></script>
        <![endif]-->
        <!--[if !IE]> -->
        <script src="/public/assets/js/jquery-2.0.3.min.js"></script>
        <!-- <![endif]-->

        <!--[if IE]>
        <script src="/public/assets/js/jquery-1.10.2.min.js"></script>
        <!-- <![endif]-->

        <script type="text/javascript">
            if("ontouchend" in document) document.write("<script src='/public/assets/js/jquery.mobile.custom.min.js'>"+"<"+"script>");
        </script>
        <script src="/public/assets/js/pjax/jquery.pjax.js"></script>
        <!-- inline scripts related to this page -->
        <script src="/public/assets/js/bootstrap.min.js"></script>
        <script src="/public/assets/js/typeahead-bs2.min.js"></script>

        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/fuelux/data/fuelux.tree-sampledata.js"></script>
        <script src="/public/assets/js/fuelux/fuelux.tree.min.js"></script>
        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/jquery-ui-1.10.3.full.min.js"></script>
        <script src="/public/assets/js/jquery.ui.touch-punch.min.js"></script>
        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/jquery.dataTables.min.js"></script>
        <script src="/public/assets/js/jquery.dataTables.bootstrap.js"></script>
        <script src="/public/assets/js/jquery.nestable.min.js"></script>
        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/date-time/bootstrap-datepicker.min.js"></script>
        <script src="/public/assets/js/jqGrid/jquery.jqGrid.min.js"></script>
        <script src="/public/assets/js/jqGrid/i18n/grid.locale-en.js"></script>
        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="/public/assets/js/chosen.jquery.min.js"></script>
        <script src="/public/assets/js/fuelux/fuelux.spinner.min.js"></script>
        <script src="/public/assets/js/date-time/bootstrap-timepicker.min.js"></script>
        <script src="/public/assets/js/date-time/moment.min.js"></script>
        <script src="/public/assets/js/date-time/daterangepicker.min.js"></script>
        <script src="/public/assets/js/bootstrap-colorpicker.min.js"></script>
        <script src="/public/assets/js/jquery.knob.min.js"></script>
        <script src="/public/assets/js/jquery.autosize.min.js"></script>
        <script src="/public/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
        <script src="/public/assets/js/jquery.maskedinput.min.js"></script>
        <script src="/public/assets/js/bootstrap-tag.min.js"></script>
        <!-- page specific plugin scripts -->
        <script src="/public/assets/js/dropzone.min.js"></script>
        <!-- ace scripts -->
        <script src="/public/assets/js/ace-elements.min.js"></script>
        <script src="/public/assets/js/ace.min.js"></script>

        <!-- common script end -->
		<script type="text/javascript">
			$(function(){
				$(document).pjax('#navi a', '#main')
		    })
		</script>
	</head>
	
	<body>
		<div class="navbar navbar-default" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>
			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
							ACE后台管理系统
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation" id="pjax">
					<ul class="nav ace-nav">
						<li class="grey">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-tasks"></i>
								<span class="badge badge-grey">4</span>
							</a>

							<ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-ok"></i>
									还有4个任务完成
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">软件更新</span>
											<span class="pull-right">65%</span>
										</div>

										<div class="progress progress-mini ">
											<div style="width:65%" class="progress-bar "></div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">硬件更新</span>
											<span class="pull-right">35%</span>
										</div>

										<div class="progress progress-mini ">
											<div style="width:35%" class="progress-bar progress-bar-danger"></div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">单元测试</span>
											<span class="pull-right">15%</span>
										</div>

										<div class="progress progress-mini ">
											<div style="width:15%" class="progress-bar progress-bar-warning"></div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">错误修复</span>
											<span class="pull-right">90%</span>
										</div>

										<div class="progress progress-mini progress-striped active">
											<div style="width:90%" class="progress-bar progress-bar-success"></div>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										查看任务详情
										<i class="icon-arrow-right"></i>
									</a>
								</li>
							</ul>
						</li>

						<li class="purple">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-bell-alt icon-animated-bell"></i>
								<span class="badge badge-important">8</span>
							</a>

							<ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-warning-sign"></i>
									8条通知
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-pink icon-comment"></i>
												新闻评论
											</span>
											<span class="pull-right badge badge-info">+12</span>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<i class="btn btn-xs btn-primary icon-user"></i>
										切换为编辑登录..
									</a>
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-success icon-shopping-cart"></i>
												新订单
											</span>
											<span class="pull-right badge badge-success">+8</span>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										<div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-info icon-twitter"></i>
												粉丝
											</span>
											<span class="pull-right badge badge-info">+11</span>
										</div>
									</a>
								</li>

								<li>
									<a href="#">
										查看所有通知
										<i class="icon-arrow-right"></i>
									</a>
								</li>
							</ul>
						</li>

						<li class="green">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-envelope icon-animated-vertical"></i>
								<span class="badge badge-success">5</span>
							</a>

							<ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-envelope-alt"></i>
									5条消息
								</li>

								<li>
									<a href="#">
										<img src="/public/assets/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
										<span class="msg-body">
											<span class="msg-title">
												<span class="blue">Alex:</span>
												不知道写啥 ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>1分钟以前</span>
											</span>
										</span>
									</a>
								</li>

								<li>
									<a href="#">
										<img src="/public/assets/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
										<span class="msg-body">
											<span class="msg-title">
												<span class="blue">Susan:</span>
												不知道翻译...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>20分钟以前</span>
											</span>
										</span>
									</a>
								</li>

								<li>
									<a href="#">
										<img src="/public/assets/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
										<span class="msg-body">
											<span class="msg-title">
												<span class="blue">Bob:</span>
												到底是不是英文 ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>下午3:15</span>
											</span>
										</span>
									</a>
								</li>

								<li>
									<a href="inbox.html">
										查看所有消息
										<i class="icon-arrow-right"></i>
									</a>
								</li>
							</ul>
						</li>

						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<img class="nav-user-photo" src="/public/assets/avatars/user.jpg" alt="Jason's Photo" />
								<span class="user-info">
									<small>欢迎光临,</small>
									<{$user.nick}>
								</span>

								<i class="icon-caret-down"></i>
							</a>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<li>
									<a href="#">
										<i class="icon-cog"></i>
										设置
									</a>
								</li>

								<li>
									<a href="#">
										<i class="icon-user"></i>
										个人资料
									</a>
								</li>

								<li class="divider"></li>

								<li>
									<a href="/index/index/doLogout">
										<i class="icon-off"></i>
										退出
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<button class="btn btn-success">
								<i class="icon-signal"></i>
							</button>

							<button class="btn btn-info">
								<i class="icon-pencil"></i>
							</button>

							<button class="btn btn-warning">
								<i class="icon-group"></i>
							</button>

							<button class="btn btn-danger">
								<i class="icon-cogs"></i>
							</button>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					<{include file='./navi.phtml'}>

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="icon-home home-icon"></i>
								<a href="#">首页</a>
							</li>
							<li class="active"><{$title}></li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="icon-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- #nav-search -->
					</div>