<{if !$pjax}>
<{include file='../Public/header.phtml'}>
<{else}>
<{/if}>
<div class="page-content" id="main">
    <div class="page-header">
        <h1>
            Gallery
            <small>
                <i class="icon-double-angle-right"></i>
                responsive photo gallery using colorbox
            </small>
        </h1>
    </div>
    <!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div class="row-fluid">
                <ul class="ace-thumbnails">
                    <li>
                        <a href="/public/assets/images/gallery/image-1.jpg" title="Photo Title" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-1.jpg"/>

                            <div class="tags">
													<span class="label-holder">
														<span class="label label-info">breakfast</span>
													</span>

													<span class="label-holder">
														<span class="label label-danger">fruits</span>
													</span>

													<span class="label-holder">
														<span class="label label-success">toast</span>
													</span>

													<span class="label-holder">
														<span class="label label-warning arrowed-in">diet</span>
													</span>
                            </div>
                        </a>

                        <div class="tools">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-2.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-2.jpg"/>

                            <div class="text">
                                <div class="inner">Sample Caption on Hover</div>
                            </div>
                        </a>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-3.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-3.jpg"/>

                            <div class="text">
                                <div class="inner">Sample Caption on Hover</div>
                            </div>
                        </a>

                        <div class="tools tools-bottom">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-4.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-4.jpg"/>

                            <div class="tags">
													<span class="label-holder">
														<span class="label label-info arrowed">fountain</span>
													</span>

													<span class="label-holder">
														<span class="label label-danger">recreation</span>
													</span>
                            </div>
                        </a>

                        <div class="tools tools-top">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>

                    <li>
                        <div>
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-5.jpg"/>

                            <div class="text">
                                <div class="inner">
                                    <span>Some Title!</span>

                                    <br/>
                                    <a href="/public/assets/images/gallery/image-5.jpg" data-rel="colorbox">
                                        <i class="icon-zoom-in"></i>
                                    </a>

                                    <a href="#">
                                        <i class="icon-user"></i>
                                    </a>

                                    <a href="#">
                                        <i class="icon-share-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-6.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-6.jpg"/>
                        </a>

                        <div class="tools tools-right">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-1.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-1.jpg"/>
                        </a>

                        <div class="tools">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>

                    <li>
                        <a href="/public/assets/images/gallery/image-2.jpg" data-rel="colorbox">
                            <img alt="150x150" src="/public/assets/images/gallery/thumb-2.jpg"/>
                        </a>

                        <div class="tools tools-top">
                            <a href="#">
                                <i class="icon-link"></i>
                            </a>

                            <a href="#">
                                <i class="icon-paper-clip"></i>
                            </a>

                            <a href="#">
                                <i class="icon-pencil"></i>
                            </a>

                            <a href="#">
                                <i class="icon-remove red"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</div><!-- /.page-content -->
</div><!-- /.main-content -->

<div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
        <i class="icon-cog bigger-150"></i>
    </div>

    <div class="ace-settings-box" id="ace-settings-box">
        <div>
            <div class="pull-left">
                <select id="skin-colorpicker" class="hide">
                    <option data-skin="default" value="#438EB9">#438EB9</option>
                    <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                    <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                    <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                </select>
            </div>
            <span>&nbsp; Choose Skin</span>
        </div>

        <div>
            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar"/>
            <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
        </div>

        <div>
            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar"/>
            <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
        </div>

        <div>
            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs"/>
            <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
        </div>

        <div>
            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl"/>
            <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
        </div>

        <div>
            <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container"/>
            <label class="lbl" for="ace-settings-add-container">
                Inside
                <b>.container</b>
            </label>
        </div>
    </div>
</div><!-- /#ace-settings-container -->
</div><!-- /.main-container-inner -->

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>
</div><!-- /.main-container -->

<div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-xs btn-warning ace-settings-btn"
         id="ace-settings-btn"><i class="icon-cog bigger-150"></i></div>

    <div class="ace-settings-box" id="ace-settings-box">
        <div>
            <div class="pull-left"><select id="skin-colorpicker" class="hide">
                    <option data-skin="default" value="#438EB9">#438EB9</option>
                    <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                    <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                    <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                </select></div>
            <span>&nbsp; Choose Skin</span></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-navbar"/> <label class="lbl"
                                                      for="ace-settings-navbar"> Fixed Navbar</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-sidebar"/> <label class="lbl"
                                                       for="ace-settings-sidebar"> Fixed Sidebar</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-breadcrumbs"/> <label class="lbl"
                                                           for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
        </div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-rtl"/> <label class="lbl" for="ace-settings-rtl">
                Right To Left (rtl)</label></div>

        <div><input type="checkbox" class="ace ace-checkbox-2"
                    id="ace-settings-add-container"/> <label class="lbl"
                                                             for="ace-settings-add-container"> Inside <b>.container</b>
            </label></div>
    </div>
</div>
<!-- /#ace-settings-container -->
</div>
<!-- /.main-container-inner -->

<a href="#" id="btn-scroll-up"
   class="btn-scroll-up btn btn-sm btn-inverse"> <i
        class="icon-double-angle-up icon-only bigger-110"></i> </a>
</div>
<!-- /.main-container -->

<!-- basic scripts -->
<!--[if !IE]> -->
<script type="text/javascript">
    window.jQuery || document.write("<script src='/public/assets/js/jquery-2.0.3.min.js'>" + "<" + "/script>");
</script>
<!-- <![endif]-->
<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='/public/assets/js/jquery-1.10.2.min.js'>" + "<" + "/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if ("ontouchend" in document) document.write("<script src='/public/assets/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>


<script type="text/javascript">
    jQuery(function ($) {
        var colorbox_params = {
            reposition: true,
            scalePhotos: true,
            scrolling: false,
            previous: '<i class="icon-arrow-left"></i>',
            next: '<i class="icon-arrow-right"></i>',
            close: '&times;',
            current: '{current} of {total}',
            maxWidth: '100%',
            maxHeight: '100%',
            onOpen: function () {
                document.body.style.overflow = 'hidden';
            },
            onClosed: function () {
                document.body.style.overflow = 'auto';
            },
            onComplete: function () {
                $.colorbox.resize();
            }
        };

        $('.ace-thumbnails [data-rel="colorbox"]').colorbox(colorbox_params);
        $("#cboxLoadingGraphic").append("<i class='icon-spinner orange'></i>");//let's add a custom loading icon

        /**$(window).on('resize.colorbox', function() {
		try {
			//this function has been changed in recent versions of colorbox, so it won't work
			$.fn.colorbox.load();//to redraw the current frame
		} catch(e){}
	});*/
    })
</script>
<div style="display: none"></div>
</body>
</html>
