<?php if(!$pjax){
	include VIEWS_PATH.'../Public/header.phtml';
}?>
<div class="page-content" id="main">
<div class="row">
<div class="col-xs-12"><!-- PAGE CONTENT BEGINS --> <!-- PAGE CONTENT ENDS -->
</div>
<!-- /.col --></div>
<!-- /.row --></div>
<!-- /.page-content -->
</div>
<!-- /.main-content -->

<?php if(!$pjax){
	include VIEWS_PATH.'../Public/footer.phtml';
}?>
<!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->



<!-- <![endif]-->

<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]> -->

<script type="text/javascript">
			window.jQuery || document.write("<script src='assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
<script
	src="http://www.ace.com/public/assets/js/bootstrap.min.js"></script>
<script
	src="http://www.ace.com/public/assets/js/typeahead-bs2.min.js"></script>

<!-- page specific plugin scripts -->

<!-- ace scripts -->

<script
	src="http://www.ace.com/public/assets/js/ace-elements.min.js"></script>
<script src="http://www.ace.com/public/assets/js/ace.min.js"></script>

<!-- inline scripts related to this page -->
</body>
</html>
