<?php if(!$pjax){
	include VIEWS_PATH.'../Public/header.phtml';
}?>
<div class="page-content" id="main">
<div class="page-header">
<h1>Grid <small> <i class="icon-double-angle-right"></i> bootstrap grid
sizing </small></h1>
</div>
<!-- /.page-header -->

<div class="row">
<div class="col-xs-12"><!-- PAGE CONTENT BEGINS -->

<div class="center">
<div class="row">
<div class="col-xs-12"><span>.col-xs-12</span></div>
</div>

<div class="row">
<div class="col-xs-1"><span>.col-xs-1</span></div>

<div class="col-xs-11"><span>.col-xs-11</span></div>
</div>

<div class="row">
<div class="col-xs-6 col-sm-2"><span>.col-xs-6.col-sm-2</span></div>

<div class="col-xs-6 col-sm-10"><span>.col-xs-6.col-sm-10</span></div>
</div>

<div class="row">
<div class="col-xs-12 col-lg-6"><span>.col-xs-12.col-lg-6</span></div>

<div class="col-xs-12 col-lg-6"><span>.col-xs-12.col-lg-6</span></div>
</div>

<div class="row">
<div class="col-xs-4"><span>.col-xs-4</span></div>

<div class="col-xs-8"><span>.col-xs-8</span></div>
</div>

<div class="row">
<div class="col-xs-5"><span>.col-xs-5</span></div>

<div class="col-xs-7"><span>.col-xs-7</span></div>
</div>

<div class="row">
<div class="col-xs-6"><span>.col-xs-6</span></div>

<div class="col-xs-6"><span>.col-xs-6</span></div>
</div>

<div class="row">
<div class="col-xs-7"><span>.col-xs-7</span></div>

<div class="col-xs-5"><span>.col-xs-5</span></div>
</div>

<div class="row">
<div class="col-xs-8"><span>.col-xs-8</span></div>

<div class="col-xs-4"><span>.col-xs-4</span></div>
</div>

<div class="row">
<div class="col-xs-9"><span>.col-xs-9</span></div>

<div class="col-xs-3"><span>.col-xs-3</span></div>
</div>

<div class="row">
<div class="col-xs-10"><span>.col-xs-10</span></div>

<div class="col-xs-2"><span>.col-xs-2</span></div>
</div>

<div class="row">
<div class="col-xs-11"><span>.col-xs-11</span></div>

<div class="col-xs-1"><span>.col-xs-1</span></div>
</div>

<div class="row">
<div class="col-xs-12"><span>.col-xs-12</span></div>
</div>
</div>

<!-- PAGE CONTENT ENDS --></div>
<!-- /.col --></div>
<!-- /.row --></div>
<!-- /.page-content -->
</div>
<!-- /.main-content -->

<?php if(!$pjax){
	include VIEWS_PATH.'../Public/footer.phtml';
}?>
<!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->



<!-- <![endif]-->

<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]> -->

<script type="text/javascript">
			window.jQuery || document.write("<script src='assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
<script
	src="http://www.ace.com/public/assets/js/bootstrap.min.js"></script>
<script
	src="http://www.ace.com/public/assets/js/typeahead-bs2.min.js"></script>

<!-- page specific plugin scripts -->

<!-- ace scripts -->

<script
	src="http://www.ace.com/public/assets/js/ace-elements.min.js"></script>
<script src="http://www.ace.com/public/assets/js/ace.min.js"></script>

<!-- inline scripts related to this page -->
<div style="display: none"></div>
</body>
</html>
